language: c

install: true

branches:
  only:
    - master
    - dev

jobs:
  include:
    - stage: build
      script: make -C clean all
    - stage: test
      script:
          - make -C clean all
          - make -C tests/ all
          - tests/test-libtrie
      
